version: '3'
services:
  page:
    image: ghost:1-alpine
    restart: always
    ports: 
      - 2368:2368
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password