# Generated by Django 4.2.4 on 2023-08-21 18:39

from django.db import migrations, models
import playlists.validators


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length_in_seconds',
            field=models.IntegerField(validators=[playlists.validators.validate_music_length]),
        ),
    ]
