# Generated by Django 4.2.4 on 2023-08-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_music_length_in_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='playlists.singer'),
        ),
    ]
